//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSD_Tema1.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constraint
    {
        public int Id { get; set; }
        public int RoleId1 { get; set; }
        public int RoleId2 { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
