//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSD_Tema1.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceForUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ResourceId { get; set; }
        public bool R { get; set; }
        public bool W { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual User User { get; set; }
    }
}
